[package]
name = "zigbee_hello_world"
version = "0.1.0"
authors = ["Frans-Willem Hardijzer <fw@hardijzer.nl>"]
edition = "2018"

[dependencies]
tokio-serial = "3.2"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-sync = "0.1"
tokio-core = "0.1"
tokio = "0.1"
bytes = "0.4"
futures = "0.1"
bitfield = "0.13"
