[package]
name = "zigbee_hello_world"
version = "0.1.0"
authors = ["Frans-Willem Hardijzer <fw@hardijzer.nl>"]
edition = "2018"

[dependencies]
tokio-serial = "3.2"
tokio = "0.1"
bytes = "0.4"
futures-preview = {version = "0.3.0-alpha.14", features=["compat"]}
bitfield = "0.13"
enum-tryfrom = "0.2"
enum-tryfrom-derive = "0.2"
