[package]
name = "zigbee_hello_world"
version = "0.1.0"
authors = ["Frans-Willem Hardijzer <fw@hardijzer.nl>"]
edition = "2018"

[dependencies]
async-std = "1.4"
futures = "0.3"
pin-project = "0.4"
nom = "5"
